Repository opengovsg/isomer, pull requests merged in 2024-10, with the labels that each got.

#773 fix(components): masthead styling changes
  packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx
Labels: component

#774 fix(components): collectionCard spacing and line truncation enhancements
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
  packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx
Labels: component

#786 Origin/adriangohjw/isom 1586 establish our standards of support
  package-lock.json
  packages/components/browser-support.md
  packages/components/package.json
  packages/components/src/presets/next/colors.ts
  packages/components/src/templates/next/components/internal/UnsupportedBrowserBanner/UnsupportedBrowserBanner.stories.tsx
  packages/components/src/templates/next/components/internal/UnsupportedBrowserBanner/UnsupportedBrowserBanner.tsx
  packages/components/src/templates/next/components/internal/UnsupportedBrowserBanner/index.tsx
  packages/components/src/templates/next/components/internal/index.ts
  packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
  packages/components/src/utils/supportedBrowsers.ts
Labels: enhancement

#797 fix(component): colour block hero variant is missing focus visible state
  packages/components/src/templates/next/components/complex/Hero/Hero.tsx
Labels: next-component

#793 fix(component): update hover colour for inverse buttons
  packages/components/src/templates/next/components/internal/Button/Button.tsx
Labels: next-component

#792 isom-1631 change copy of title for fixed blocks in articlecontent
  apps/studio/public/assets/css/preview-tw.css
  apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx
  apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
  apps/studio/src/features/editing-experience/data/articleLayoutPreview.json
  apps/studio/src/features/editing-experience/data/collectionPdfPreview.json
  apps/studio/src/server/modules/collection/collection.service.ts
  apps/studio/src/server/modules/page/page.service.ts
  apps/studio/tests/msw/handlers/page.ts
  packages/components/src/engine/metadata.ts
  packages/components/src/interfaces/internal/ArticlePageHeader.ts
  packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.stories.tsx
  packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx
  packages/components/src/templates/next/layouts/Article/Article.stories.tsx
  packages/components/src/types/page.ts
  tooling/build/scripts/generate-sitemap.js
  tooling/build/scripts/publishing/index.ts
Labels: enhancement

#791 Add test for packages/components
  .github/workflows/ci.yml
  package-lock.json
  packages/components/package.json
  packages/components/src/utils/__tests__/getParsedData.test.ts
  packages/components/src/utils/__tests__/isExternalUrl.test.ts
  packages/components/turbo.json
  packages/components/vitest.config.ts
Labels: enhancement

#799 fix - datadog RUM check for process first
  packages/components/src/templates/next/components/internal/DatadogRum/DatadogRum.tsx
Labels: bug

#798 Fix unsupported browser flashing bug
  packages/components/src/templates/next/components/internal/UnsupportedBrowserBanner/UnsupportedBrowserBanner.stories.tsx
  packages/components/src/templates/next/components/internal/UnsupportedBrowserBanner/UnsupportedBrowserBanner.tsx
  packages/components/src/utils/__tests__/isSupportedBrowser.test.ts
  packages/components/src/utils/isSupportedBrowser.ts
Labels: bug

#796 isom-1637 bug html tags from tiptap editor not stripped
  packages/components/src/interfaces/native/Prose.ts
  packages/components/src/templates/next/components/native/Prose/Prose.tsx
  packages/components/src/templates/next/render/render.tsx
  packages/components/src/utils/getTextAsHtml.ts
Labels: bug

#802 fix(component): update site notification background so it doesn't blend in with masthead
  packages/components/src/presets/next/colors.ts
  packages/components/src/templates/next/components/internal/Notification/Notification.tsx
Labels: next-component

#804 fix- replace dom manipulation with DOMPurify to make it server-safe
  packages/components/src/utils/getTextAsHtml.ts
Labels: bug

#794 isom-1619 keystatistics should have a link out to a page
  apps/studio/public/assets/css/preview-tw.css
  packages/components/src/interfaces/complex/KeyStatistics.ts
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Labels: enhancement

#805 fix - add missing args for KeyStats getReferenceLinkHref call
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Labels: bug

#801 isom-1639 infocards on homepage have a short image height when in 2
  packages/components/src/interfaces/complex/InfoCards.ts
  packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx
  packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx
Labels: enhancement

#800 isom-1624 remove year filter for non date variant of collections
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
  packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx
  packages/components/src/templates/next/layouts/Collection/Collection.tsx
  packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
  packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
  packages/components/src/templates/next/layouts/Collection/utils.ts
Labels: enhancement

#816 Add resource permission to seed
  apps/studio/prisma/seed.ts
Labels: enhancement

#820 Fix studio article editing space
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAccordionTextControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAnyOfControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsCalloutTextControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsDateControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsIntegerControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsLinkControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsProseControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsRefControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextAreaControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsGroupLayout.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsVerticalLayout.tsx
  apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx
  apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx
Labels: bug

#824 isom-1633 - studio select layout page is using old template designs
  apps/studio/public/assets/layout-card/article_layout_card.webp
  apps/studio/public/assets/layout-card/default_layout_card.webp
Labels: enhancement

#819 isom-1636 database layout gets an extra spacing when theres no title
  packages/components/src/templates/next/components/internal/SearchableTable/SearchableTable.stories.tsx
  packages/components/src/templates/next/components/internal/SearchableTable/SearchableTableClient.tsx
  packages/components/src/templates/next/layouts/Database/Database.stories.tsx
Labels: enhancement

#825 improvement (perf) - move filters to server side
  packages/components/src/templates/next/layouts/Collection/Collection.tsx
  packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
  packages/components/src/templates/next/layouts/Collection/useCollection.ts
Labels: enhancement

#807 attempt to support flex gap in tailwind
  apps/studio/public/assets/css/preview-tw.css
  packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
  packages/components/tailwind.config.ts
  tooling/template/tailwind.config.js
Labels: enhancement

#810 Polyfill colors
  apps/studio/public/assets/css/preview-tw.css
  package-lock.json
  packages/components/package.json
  packages/components/postcss.config.js
  packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx
  tooling/template/package.json
  tooling/template/postcss.config.js
Labels: enhancement

#827 Allow editing of keystats CTA text
  apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx
  packages/components/src/interfaces/complex/KeyStatistics.ts
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Labels: enhancement

#830 isom-1650 - Old browser (iphone7) keystats mobile design broken
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Labels: bug

#840 replace with RoleType for SSOT
  apps/studio/src/server/modules/permissions/__tests__/permissions.service.test.ts
  apps/studio/src/server/modules/permissions/permissions.service.ts
  apps/studio/src/server/modules/permissions/permissions.util.ts
  apps/studio/tests/integration/helpers/seed/index.ts
Labels: enhancement

#846 isom-1651 - add acceptable file type messages
  apps/studio/src/components/PageEditor/FileAttachment.tsx
Labels: enhancement

#848 Refactor client components to reduce build size
  packages/components/src/interfaces/internal/Navbar.ts
  packages/components/src/interfaces/internal/Notification.ts
  packages/components/src/interfaces/internal/index.ts
  packages/components/src/templates/next/components/complex/Image/ImageClient.tsx
  packages/components/src/templates/next/components/internal/Navbar/MobileNavMenu/MobileNavItemAccordion.tsx
  packages/components/src/templates/next/components/internal/Navbar/MobileNavMenu/MobileNavbarMenu.tsx
  packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx
  packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
  packages/components/src/templates/next/components/internal/Navbar/NavbarClient.tsx
  packages/components/src/templates/next/components/internal/Notification/Notification.stories.tsx
  packages/components/src/templates/next/components/internal/Notification/Notification.tsx
  packages/components/src/templates/next/components/internal/Notification/NotificationClient.tsx
  packages/components/src/templates/next/components/native/Table/Table.tsx
Labels: enhancement
