Repository opengovsg/isomer, pull requests merged in 2024-11, with the labels that each got.

#838 replace with ResourceType for SSOT
  apps/studio/src/components/PageEditor/ComponentSelector.tsx
  apps/studio/src/components/ResourceSelector/ResourceItem.tsx
  apps/studio/src/components/ResourceSelector/ResourceSelector.tsx
  apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx
  apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebar.tsx
  apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebarContent.tsx
  apps/studio/src/features/dashboard/components/DirectorySidebar/useIsActive.ts
  apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx
  apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx
  apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx
  apps/studio/src/features/editing-experience/components/EditLinkPreview.tsx
  apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx
  apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
  apps/studio/src/pages/sites/[siteId]/index.tsx
  apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx
  apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx
  apps/studio/src/pages/sites/[siteId]/settings.tsx
  apps/studio/src/server/modules/collection/collection.router.ts
  apps/studio/src/server/modules/folder/folder.router.ts
  apps/studio/src/server/modules/page/page.router.ts
  apps/studio/src/server/modules/resource/resource.router.ts
  apps/studio/src/server/modules/resource/resource.service.ts
  apps/studio/src/utils/resource.ts
  apps/studio/src/utils/sitemap.ts
  apps/studio/tests/integration/helpers/seed/index.ts
Labels: enhancement

#853 import ResourceType
  apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx
Labels: bug

#831 isom-1514 - add highlighted text for link insertion in tiptap
  apps/studio/src/components/PageEditor/MenuBar/TiptapLinkEditorModal.tsx
Labels: enhancement

#862 speed up codebuild - aws s3 sync higher concurrency
  tooling/build/scripts/publisher.sh
Labels: enhancement

#832 refactor - use const for linktype
  apps/studio/src/components/PageEditor/MenuBar/TiptapLinkEditorModal.tsx
  apps/studio/src/features/editing-experience/components/LinkEditor/LinkHrefEditor.tsx
  apps/studio/src/features/editing-experience/components/LinkEditor/LinkTypeRadioContent.tsx
  apps/studio/src/features/editing-experience/components/LinkEditor/constants.ts
  apps/studio/src/features/editing-experience/components/LinkEditor/utils.ts
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsLinkControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsRefControl.tsx
Labels: enhancement

#873 Fix dependabot yml
  .github/dependabot.yml
Labels: bug

#871 reduce cloudfront cost (move collection processing to server-side)
  packages/components/src/interfaces/internal/CollectionCard.ts
  packages/components/src/interfaces/internal/index.ts
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
  packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx
  packages/components/src/templates/next/layouts/Collection/Collection.tsx
  packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
  packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
  packages/components/src/templates/next/layouts/Collection/useCollection.ts
  packages/components/src/templates/next/layouts/Collection/utils.ts
Labels: enhancement

#867 isom-1655 display block contents for identification
  apps/studio/src/features/editing-experience/components/Block/BaseBlock.tsx
  apps/studio/src/features/editing-experience/components/Block/DraggableBlock.tsx
  apps/studio/tests/msw/handlers/page.ts
  packages/components/src/engine/index.ts
  packages/components/src/engine/render.tsx
  packages/components/src/interfaces/native/index.ts
  packages/components/src/templates/next/render/index.ts
  packages/components/src/templates/next/render/renderComponentPreviewText.ts
Labels: enhancement

#858 cache `node_modules` to reduce build time
  apps/studio/src/server/modules/aws/codebuild.service.ts
  tooling/build/scripts/publisher.sh
Labels: enhancement

#880 Studio - only show intercom post-login
  apps/studio/src/components/AuthWrappers/EnforceLoginStatePageWrapper.tsx
  apps/studio/src/pages/_app.tsx
Labels: enhancement

#890 Intercom - Add user info
  apps/studio/src/components/AuthWrappers/EnforceLoginStatePageWrapper.tsx
  apps/studio/src/components/Intercom.tsx
  apps/studio/src/server/modules/me/me.select.ts
Labels: enhancement

#891 update _next to be cached indefinitely
  tooling/build/scripts/publisher.sh
Labels: enhancement

#875 global search backend
  apps/studio/prisma/migrations/20241114155239_resource_title_add_trgm_index/migration.sql
  apps/studio/src/schemas/resource.ts
  apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts
  apps/studio/src/server/modules/resource/resource.router.ts
  apps/studio/src/server/modules/resource/resource.service.ts
  apps/studio/src/server/modules/resource/resource.types.ts
  apps/studio/src/server/modules/site/site.router.ts
  apps/studio/src/server/modules/site/site.service.ts
  apps/studio/tests/integration/helpers/seed/index.ts
Labels: enhancement

#882 Feat/search fe
  apps/studio/package.json
  apps/studio/src/components/AppBanner.tsx
  apps/studio/src/components/CmsSidebar/CmsContainer.tsx
  apps/studio/src/components/CmsSidebar/CmsSidebar.tsx
  apps/studio/src/components/CmsSidebar/index.tsx
  apps/studio/src/components/Searchbar/SearchModal.tsx
  apps/studio/src/components/Searchbar/SearchModalBodyContentStates.tsx
  apps/studio/src/components/Searchbar/SearchResult.tsx
  apps/studio/src/components/Searchbar/Searchbar.tsx
  apps/studio/src/components/Searchbar/index.ts
  apps/studio/src/components/Searchbar/isMac.ts
  apps/studio/src/components/Searchbar/useSearchStyle.ts
  apps/studio/src/components/Svg/NoSearchResultSvgr.tsx
  apps/studio/src/hooks/useBanner.ts
  apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx
  apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
  apps/studio/src/pages/sites/[siteId]/index.tsx
  apps/studio/src/schemas/site.ts
  apps/studio/src/server/modules/site/__tests__/site.router.test.ts
  apps/studio/src/server/modules/site/site.router.ts
  apps/studio/src/stories/Flows/CreateCollectionItemFlow.stories.tsx
  apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx
  apps/studio/src/stories/Page/Search.stories.tsx
  apps/studio/src/stories/Page/SitePage.stories.tsx
  apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx
  apps/studio/src/theme/components/Searchbar.ts
  apps/studio/src/theme/components/index.ts
  apps/studio/src/utils/formatDate.ts
  apps/studio/src/utils/resources.ts
  apps/studio/tests/msw/handlers/resource.ts
  apps/studio/tests/msw/handlers/sites.ts
  package-lock.json
Labels: enhancement

#894 isom-1675 - add GTM components
  packages/components/src/interfaces/internal/GoogleTagManager.ts
  packages/components/src/interfaces/internal/index.ts
  packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerBody.tsx
  packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerHeader.tsx
  packages/components/src/templates/next/components/internal/GoogleTagManager/index.ts
  packages/components/src/templates/next/components/internal/index.ts
  packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
  packages/components/src/types/site.ts
  tooling/template/app/[[...permalink]]/page.tsx
  tooling/template/app/not-found.tsx
Labels: enhancement

#860 upgrade to next15
  apps/studio/next.config.mjs
  package-lock.json
  package.json
  tooling/template/app/[[...permalink]]/page.tsx
  tooling/template/app/layout.tsx
  tooling/template/app/not-found.tsx
  tooling/template/app/robots.ts
  tooling/template/app/sitemap.ts
  tooling/template/package.json
Labels: enhancement, dependencies

#899 isom-1683 arabic auto RTL display
  apps/studio/package.json
  apps/studio/src/features/editing-experience/hooks/useTextEditor.ts
  package-lock.json
  packages/components/src/interfaces/internal/AttrsDir.ts
  packages/components/src/interfaces/internal/index.ts
  packages/components/src/interfaces/native/Heading.ts
  packages/components/src/interfaces/native/Paragraph.ts
  packages/components/src/templates/next/components/internal/BaseParagraph/BaseParagraph.tsx
  packages/components/src/templates/next/components/native/Heading/Heading.stories.tsx
  packages/components/src/templates/next/components/native/Heading/Heading.tsx
  packages/components/src/templates/next/components/native/Paragraph/Paragraph.stories.tsx
  packages/components/src/templates/next/components/native/Paragraph/Paragraph.tsx
  packages/components/src/templates/next/components/native/Prose/Prose.tsx
Labels: enhancement

#900 intercom drop preferredname
  apps/studio/prisma/generated/generatedTypes.ts
  apps/studio/prisma/generated/selectableTypes.ts
  apps/studio/prisma/migrations/20241126162857_drop_preferred_name_column/migration.sql
  apps/studio/prisma/migrations/20241127035129_drop_site_member_table/migration.sql
  apps/studio/prisma/schema.prisma
  apps/studio/src/components/Intercom.tsx
  apps/studio/src/server/modules/me/me.select.ts
  apps/studio/tests/integration/helpers/iron-session.ts
  apps/studio/tests/msw/handlers/me.ts
Labels: enhancement

#906 fix - no spacing between title and cross button for movemodal
  apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx
Labels: bug
