Repository opengovsg/isomer, pull requests merged in 2025-02, with the labels that each got.

#999 Enhancement/add user email in studio
  apps/studio/src/components/AppNavbar.tsx
  apps/studio/src/components/AvatarMenu.tsx
  apps/studio/src/components/SearchableHeader.tsx
  apps/studio/src/stories/Page/SitePage.stories.tsx
Labels: enhancement

#1006 Chore tweak dynamicdatabanner UI (mobile view)
  apps/studio/public/assets/css/preview-tw.css
  packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.stories.tsx
  packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBannerClient.tsx
  packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
  tooling/storybook/modes.ts
Labels: bug

#1065 Feat/admin create index page temp workabout
  apps/studio/src/features/dashboard/components/AdminCreateIndexPageButton.tsx
  apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx
  apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
  apps/studio/src/schemas/page.ts
  apps/studio/src/schemas/resource.ts
  apps/studio/src/server/modules/page/page.router.ts
  apps/studio/src/server/modules/resource/resource.router.ts
Labels: enhancement

#1068 fix - remove conditional check for resoucetype
  apps/studio/src/server/modules/page/page.router.ts
Labels: bug

#1072 fix - add custom error message for JsonFormsTextAreaControl
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextAreaControl.tsx
Labels: bug

#1085 fix - add explicit 5000ms timeout for growthbook
  apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx
  apps/studio/src/stories/Page/EditPage/EditCollectionLink.stories.tsx
Labels: bug

#1084 isom-1723 - fix studio table buttons disappear on smaller screen
  apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx
  apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx
Labels: bug

#1083 isom-1574 - fix: add hover color for datatable
  apps/studio/src/components/Datatable/Datatable.tsx
Labels: bug

#1086 vica: support asset URL + use site color + fix disappearing between navigation
  packages/components/src/interfaces/internal/Vica.ts
  packages/components/src/interfaces/internal/index.ts
  packages/components/src/templates/next/components/internal/Vica/VicaWidget.tsx
  packages/components/src/templates/next/components/internal/Vica/VicaWidgetClient.tsx
  packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
  packages/components/src/types/site.ts
Labels: enhancement

#1091 fix - sign in page not full width
  apps/studio/src/pages/sign-in/index.tsx
Labels: bug

#1117 isom-1740 backend user management service (tracking last login)
  apps/studio/prisma/generated/generatedTypes.ts
  apps/studio/prisma/migrations/20250218133951_add_user_last_login_at/migration.sql
  apps/studio/prisma/schema.prisma
  apps/studio/src/components/ErrorBoundary/DefaultTrpcError.tsx
  apps/studio/src/features/editing-experience/components/PublishButton.tsx
  apps/studio/src/features/editing-experience/components/form-builder/components/LinkErrorBoundary.tsx
  apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts
  apps/studio/src/server/modules/auth/email/email.router.ts
  apps/studio/src/server/modules/auth/sgid/__tests__/sgid.service.test.ts
  apps/studio/src/server/modules/auth/sgid/sgid.service.ts
  apps/studio/tests/integration/helpers/iron-session.ts
  apps/studio/tests/msw/handlers/me.ts
Labels: enhancement

#1121 isom-1740 backend user management service (API endpoints)
  apps/studio/src/schemas/user.ts
  apps/studio/src/server/modules/permissions/permissions.service.ts
  apps/studio/src/server/modules/permissions/permissions.type.ts
  apps/studio/src/server/modules/user/__tests__/user.router.test.ts
  apps/studio/src/server/modules/user/__tests__/user.service.test.ts
  apps/studio/src/server/modules/user/user.router.ts
  apps/studio/src/server/modules/user/user.service.ts
  apps/studio/src/utils/__tests__/email.test.ts
  apps/studio/tests/integration/helpers/iron-session.ts
  apps/studio/tests/integration/helpers/seed/index.ts
  apps/studio/tests/msw/constants.ts
Labels: enhancement

#1123 isom-1739 USER MGMT (backend email notification service)
  apps/studio/src/features/mail/service.ts
  apps/studio/src/features/mail/templates/__tests__/templates.test.ts
  apps/studio/src/features/mail/templates/index.ts
  apps/studio/src/features/mail/templates/templates.ts
  apps/studio/src/features/mail/templates/types.ts
  apps/studio/src/lib/mail.ts
Labels: enhancement

#1132 [component] update footer copy
  packages/components/src/templates/next/components/internal/Footer/Footer.tsx
Labels: next-component

#1124 [component] add white background to infocards to remove inner shadow when image-fit: contain
  packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx
Labels: next-component

#1126 [component] entire CollectionCard / BlogCard should be clickable
  apps/studio/public/assets/css/preview-tw.css
  package-lock.json
  packages/components/.storybook/main.ts
  packages/components/package.json
  packages/components/src/templates/next/components/internal/BlogCard/BlogCard.stories.tsx
  packages/components/src/templates/next/components/internal/BlogCard/BlogCard.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
Labels: next-component

#1139 isom-1727 bug external link all should have new tab icon open in new
  apps/studio/public/assets/css/preview-tw.css
  packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx
  packages/components/src/templates/next/components/complex/Infobar/Infobar.stories.tsx
  packages/components/src/templates/next/components/complex/Infopic/Infopic.stories.tsx
  packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx
  packages/components/src/templates/next/components/internal/BlogCard/BlogCard.stories.tsx
  packages/components/src/templates/next/components/internal/BlogCard/BlogCard.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/Title/ExternalLinkTitle.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/Title/InternalLinkTitle.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/Title/Title.tsx
  packages/components/src/templates/next/components/internal/CollectionCard/Title/collectionCardLinkStyle.ts
  packages/components/src/templates/next/components/internal/CollectionCard/Title/index.ts
  packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.stories.tsx
  packages/components/src/templates/next/components/internal/LinkButton/LinkButton.stories.tsx
  packages/components/src/templates/next/components/internal/LinkButton/LinkButton.tsx
  packages/components/src/templates/next/layouts/Content/Content.stories.tsx
  packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
Labels: bug

#1140 Enhance/collection alphabetical sorting
  packages/components/src/templates/next/layouts/Collection/Collection.tsx
  packages/components/src/templates/next/layouts/Collection/utils/getCollectionItems.ts
  packages/components/src/templates/next/layouts/Collection/utils/index.ts
Labels: bug

#865 isom-1659 internal links for folders
  apps/studio/src/components/ErrorBoundary/DefaultTrpcError.tsx
  apps/studio/src/components/PageEditor/LinkEditorModal.tsx
  apps/studio/src/components/ResourceSelector/ResourceItem.tsx
  apps/studio/src/components/ResourceSelector/ResourceSelector.tsx
  apps/studio/src/components/ResourceSelector/ResourceSelectorContent.tsx
  apps/studio/src/components/ResourceSelector/ResourceSelectorHeader.tsx
  apps/studio/src/components/ResourceSelector/SearchBar.tsx
  apps/studio/src/components/ResourceSelector/useResourceQuery.tsx
  apps/studio/src/components/ResourceSelector/useResourceSelector.tsx
  apps/studio/src/components/ResourceSelector/useResourceStack.tsx
  apps/studio/src/components/ResourceSelector/utils/index.ts
  apps/studio/src/components/ResourceSelector/utils/lastResourceItemInAncestryStack.ts
  apps/studio/src/components/Searchbar/SearchModal.tsx
  apps/studio/src/components/Searchbar/SearchResult.tsx
  apps/studio/src/features/dashboard/components/CollectionTable/CollectionTableMenu.tsx
  apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebarContent.tsx
  apps/studio/src/features/dashboard/components/DirectorySidebar/constants.ts
  apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx
  apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx
  apps/studio/src/features/editing-experience/atoms.ts
  apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/TypeOptionsInput.tsx
  apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx
  apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx
  apps/studio/src/features/editing-experience/components/PublishButton.tsx
  apps/studio/src/features/editing-experience/components/form-builder/components/LinkErrorBoundary.tsx
  apps/studio/src/features/editing-experience/types.ts
  apps/studio/src/hooks/useSearchQuery.ts
  apps/studio/src/schemas/resource.ts
  apps/studio/src/server/modules/folder/__tests__/folder.router.test.ts
  apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts
  apps/studio/src/server/modules/resource/__tests__/resource.service.test.ts
  apps/studio/src/server/modules/resource/resource.router.ts
  apps/studio/src/server/modules/resource/resource.service.ts
  apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx
  apps/studio/src/stories/Page/EditPage/EditCollectionLink.stories.tsx
  apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx
  apps/studio/src/stories/Page/MoveResourceModal.stories.tsx
  apps/studio/src/utils/resources.ts
  apps/studio/tests/integration/helpers/seed/index.ts
  apps/studio/tests/msw/handlers/resource.ts
Labels: enhancement

#1143 fix: studio file/image upload acceptable file extension copywriting
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsMetaImageControl.tsx
  apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/constants.ts
Labels: bug

#1144 Improve muis prayers banner UI
  apps/studio/public/assets/css/preview-tw.css
  packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.stories.tsx
  packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBannerClient.tsx
  packages/components/src/templates/next/components/internal/SearchableTable/SearchableTableClient.tsx
Labels: enhancement

#1145 fix: Dynamically display accepted file types in FileAttachment
  apps/studio/src/components/PageEditor/FileAttachment.tsx
Labels: bug
